<a href="https://colab.research.google.com/github/SeleneCampos/TensorFlow/blob/main/TensorFlow_s1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensors

"A tensor is a generalization of vectors and matrices to pontentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It shouldn't surprise you that tensors are a fundemental aspect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to bbe generated.

Each Tensor has a data type and a shape.

**Data Types Include:** float 32, int32, string and others.

**Shape:** Represents the dimension of data.

In [2]:
import tensorflow as tf
tf.dtypes.DType?

### Creating Tensors

Below is an example of how to create some different tensors.

In [ ]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)


In [ ]:
print("string: ", string)
print(f"number: {number}")
print("floating: ", floating)

string:  <tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
number: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
floating:  <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


### Rank/Degree of Tensors

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created abbobve is a tensor of rank 0, also kwonw as scalar

Now we'll create some tensors of higher degrees/ranks

In [9]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok", "Selene"], ["test", "yes", "ok"]], tf.string)

**To determine the rank** of a tensor wee can call the following method.

In [5]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Shape of Tensors

Now that we've talked about the rank of tensors it's time to talk about the shape. The shape of a tensor is simply the amount of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unkwnown.

To **get the shape** of a tensor we use the shape attribute

In [10]:
rank2_tensor.shape

TensorShape([2, 3])

### Changing Shape

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convenient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor

In [33]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape exixsting data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3,-1])   # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]

# The number of elements in the reshaped tensor MUST match the number in the original

In [32]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]], shape=(6, 1), dtype=float32)


### Types of Tensors

Before we go to far I will mention that there are different types of tensors. These are most commonly used and we will talk more in depth about each as they are used.


*   Variable
*   Constant
*   Placeholder
*   SparseTensor

With the exception of **Variable** all of these tensors are immuttable, meaning their value may not change during execution.

For now it is sufficient to understand that we use the Variable tensor when we want to potencially change the value of our tensor





### Evaluating Tensors

There will be some times throughout this guide that we need to evaluate a tensor. In other words, get its value. Since tensors represent a partially complete computation we will sometimes need to run what's called a session to evaluate the tensor.

There are many different ways to achieve this but I will note the simplest way below.

In [35]:
with tf.Session() as sess: # creates a session using the default graph
  tensor.eval() # tensor will of course bbe the name of your tensor

In the code above we evaluated the tensor variable that was stored in the **default graph**. The default graph holds all operations not specififed to any other graph. It is possible to create our own separate graphs but for now we will stick with the default.


### Sources

Most of the information is taken directly from the TensorFlow website wich can be found below.

http://www.tensorflow.org/guide/tensor